spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userBD
    username: postgres
    password: Vlad132102
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true